name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Fail on nested package-lock.json inside node_modules
        run: |
          if find . -type f -name 'package-lock.json' -path '*/node_modules/*' -print -quit | grep -q .; then
            echo "ERROR: Found nested package-lock.json inside node_modules. Please remove it and commit the root package-lock.json only.";
            find . -type f -name 'package-lock.json' -path '*/node_modules/*' -print;
            exit 1;
          fi

      - name: Quick sanity - list root package.json
        run: |
          echo "root package.json:";
          jq -r '.name + "@" + .version' package.json || true
