name: Keep Scout Alive

on:
  schedule:
    # Ping every 15 minutes to prevent Azure App Service from sleeping
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Scout Keep-Alive Endpoint
      run: |
        echo "🏓 Pinging Scout to keep Azure App Service awake..."
        
        # Replace with your actual Azure App Service URL
        SCOUT_URL="https://scout-companion.azurewebsites.net"
        
        # Ping the keep-alive endpoint
        response=$(curl -s -o /dev/null -w "%{http_code}" "${SCOUT_URL}/ping" || echo "000")
        
        if [ "$response" = "200" ]; then
          echo "✅ Scout is alive! HTTP $response"
        else
          echo "⚠️ Scout might be sleeping or having issues. HTTP $response"
          echo "Trying root endpoint..."
          response2=$(curl -s -o /dev/null -w "%{http_code}" "${SCOUT_URL}/" || echo "000")
          echo "Root endpoint response: HTTP $response2"
        fi
        
        echo "🕐 Next ping in 15 minutes"
